version: '3'

services:

  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 80:3000
    volumes: 
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db:Z
    ports:
      - 27017:27017
